# Generated by Django 4.1.5 on 2023-01-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_product_productpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.product')),
            ],
        ),
        migrations.AddField(
            model_name='pricing',
            name='products',
            field=models.ManyToManyField(to='pricing.product'),
        ),
        migrations.DeleteModel(
            name='ProductPricing',
        ),
        migrations.AddField(
            model_name='product',
            name='business_activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pricing.businessactivity'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='pricing.category'),
        ),
    ]
