# Generated by Django 4.1.5 on 2023-01-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_businessactivity_category_productprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.businessactivity'),
        ),
    ]
