# Generated by Django 4.1.5 on 2023-01-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_product_business_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='products',
            field=models.ManyToManyField(blank=True, to='pricing.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='pricing.category'),
        ),
    ]
