# Generated by Django 4.1.5 on 2023-01-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_productprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://picsum.photos/200/300', max_length=300),
        ),
    ]
