# Generated by Django 4.1.5 on 2023-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://picsum.photos/700/500', max_length=300),
        ),
    ]
